import { test, expect } from "@playwright/test";
import type { Market, User, Currency } from "../types/";
import marketJson from "../data/markets.json" with {type: "json"};
import usersJson from "../data/users.json" with {type: "json"};

const markets = marketJson as Market[];
const users = usersJson as User[];

const standardUser = users.find((u) => u.username === "standard_user");

// Guard clause
if (!standardUser) {
    throw new Error("data/users.json doesn't include a username called standard_user");
}

/* if(standardUser){
    users.find((u) => u.username === "standard_user");
}else{
    throw new Error("data/users.json doesn't include a username called standard_user");
} */

const currencySymbol: Partial<Record<Currency, string>> = {
    MXN: "$",
    JPY: "¥",//"￥",
}

test.describe("Parametrized smoke per market", () => {
    for (const market of markets) {
        // String Interpolation
        test(`TC-${market.code} - logitn + catalog in market ${market.code}`, { tag: "@smoke" }, async ({ page }) => {
            // Arrange
            await page.goto("/");

            // Act
            await page.getByTestId("username-desktop").fill(standardUser.username);
            await page.getByTestId("password-desktop").fill(standardUser.password);

            await page.getByTestId(`market-${market.code}`).click();

            await page.getByTestId("login-button-desktop").click();

            // Assert
            await expect(page).toHaveURL(/\/catalog/);

            const pizzaCards = page.locator("[data-testid^='pizza-card-']");
            await expect(pizzaCards.first()).toBeVisible();

            const allCards = await pizzaCards.all();
            expect(allCards.length).toBeGreaterThanOrEqual(12);//.toBeGreaterThan(11);
        })
    }

    test('test generated by codegen', async ({ page }) => {
        await page.goto('https://omnipizza-frontend.onrender.com/');
        await page.getByTestId('user-locked_out_user').click();
        await page.getByTestId('market-CH').click();
        await page.getByTestId('login-button-desktop').click();
        await expect(page.getByTestId('login-error')).toContainText('Invalid');
    });

    test("Locators Reference", async ({ page }) => {
        await page.goto("/")
        await page.getByRole("button", { name: "Sign In" })//.click();
    
        const welcomeHeading = page.getByRole("heading", { name: "Welcome back!", level: 2});
        console.log(await welcomeHeading.innerHTML())

        const craftText = page.getByRole("heading", {level: 1});
        console.log(await craftText.textContent());

        await page.getByRole("textbox", { name: "standard_user"}).fill("locked_out_user");

        await page.getByPlaceholder("standard_user").fill("problem_user");
        await page.getByPlaceholder("••••••••").fill("pizza123");

        const userNameLabel = page.getByText("Username");
        console.log(await userNameLabel.textContent());

        const pleaseEnterDetails = page.getByText("Please enter your details", {exact: true});
        console.log(await pleaseEnterDetails.innerHTML());


        await page.getByRole("button", { name: /sign in/i }).click();
    });

    test("More locators", async ({ page }) =>{
        // Arrange
    await page.goto("/");

    // Act
    await page.getByTestId("username-desktop").fill(standardUser.username);
    await page.getByTestId("password-desktop").fill(standardUser.password);

    await page.getByTestId("market-MX").click();

    await page.getByTestId("login-button-desktop").click();

    const peperoniPizza = page.getByAltText("Pepperoni");
    await expect(peperoniPizza).toHaveAttribute('alt', /Pepp/);

    const pizzaCards = page.locator("[data-testid^='pizza-card-']");
    await expect(pizzaCards.nth(2)).toBeVisible();
    await expect(pizzaCards.filter({hasText: "Pepperoni"})).toBeVisible();

    await expect(page.getByRole("heading", {level: 3}).filter({hasText: "Quesos"})).toBeVisible();

    await page.getByRole("link", {name:"Finalizar Compra"}).click();
    });
})

